# A list containing all the food materials thar are blocked from eating while a player is in combat
blockedEnchants:
- 48
- 50
- 51
- 49
- 16
- 18
- 17
- 20
- 19
- 21
- 0
- 3
- 2
- 1
- 4
options:
  arrowDamage: 6
  arrowDamageOnlyPlayer: true
  bowCooldown: 5
  combatDuration: 5
  loginCooldown: 60
  vehicleDespawnTime: 100
  alwaysLoginPermission: darktide.admin.alwayslogin
  balanceCommandPermission: darktide.simplethings.balancecommands
  commandAccessPermission: darktide.admin.blockedcommands
  blockFireBreaking: true
  blockPistonCrossing: true
  blockFromToCrossing: true
  combatResetFoodCooldown: true
  foodMessageCooldown: 0.5
  bowMessageCooldown: 1.0
  balanceBlockedCommandMessage: §cYou don't have enough coins to use this command.
  blockedCommandMessage: §7This command is not available.
  blockedFoodMessage: §cYou cannot eat while in combat!
  bowCooldownMessage: §7Your bow is too strained. You can shoot again in §6%s§7 seconds.
  combatEnterMessage: §7You just entered combat.
  combatFadeMessage: §7You are no longer in combat.
  foodCooldownMessage: §7You are eating too fast. Try again in §6%s§7 seconds.
  loginCooldownMessage: You can login again in %s seconds.
  log:
    loginCooldown: 5
    shouldDelayRelogMessages: true
    relogDelay: 5
  bedHealing:
    HealAmount: 1
    SecondsPerHeal: 1
  enchantments: {}
  enderpearl:
    blockedRegions: []
  mobclearer:
    region: darktidecitadel
    repeatTimer: 12000
    exceptionList: []
  shouldHaveDurability:
  - 5
  - 6
  - 17
  - 18
  - 35
  - 43
  - 44
  - 76
  - 93
  - 94
  - 97
  - 256
  - 257
  - 258
  - 259
  - 263
  - 267
  - 268
  - 269
  - 270
  - 271
  - 272
  - 273
  - 274
  - 275
  - 276
  - 278
  - 279
  - 283
  - 284
  - 285
  - 286
  - 290
  - 291
  - 292
  - 293
  - 294
  - 298
  - 299
  - 300
  - 301
  - 302
  - 303
  - 304
  - 305
  - 306
  - 307
  - 308
  - 309
  - 310
  - 311
  - 312
  - 313
  - 314
  - 315
  - 316
  - 317
  - 351
  - 356
  - 373
  - 374
  - 379
  - 383
blockedCommands: []
positiveBalanceCommands: []
regionCrossingExceptions: []
